### ISSUE TITLE
contact_me_static

### ISSUE THREAD

**Issue by drewwells** [digitalcraftsman/hugo-freelancer-theme#3]
Referenced in a partial, but does not exist https://github.com/digitalcraftsman/hugo-freelancer-theme/blob/master/layouts/partials/js.html#L11. Not sure if this file is intended to be created or simply pointed to contact_me.js

**Comment by digitalcraftsman** [comment]
Thanks for mentioning this issues. The original theme contained both files but I linked the wrong one. Now the issue should be fixed with the latest commit I've made.
