### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by alanmcginnis** [digitalcraftsman/hugo-freelancer-theme#7]
Thanks for this theme! The only issue that I am having is that the category description in the modal doesn't link to anything but has anchor tag wrapped around it in the partial file. I added an archetype but I receive an error when i try to add it to the individual project yaml file. Here is the error: mapping values are not allowed in this context. I apologize if this is something simple, this is my first project with Hugo.

**Comment by digitalcraftsman** [comment]
Hello @alanmcginnis,

currently I'm not sure what exactly you want to link in the description of the modals. Normally, you can link to any source you want with plain Markdown (look [here](https://github.com/digitalcraftsman/hugo-freelancer-theme/blob/master/exampleSite/data/projects/2014-07-13-project-1.yaml#L8)).

If this doesn't solve your issue please give me a few more hints for spotting the problem.

**Comment by alanmcginnis** [comment]
Thanks for the quick reply. I am referencing line 7 **category** in the [yaml file](https://github.com/digitalcraftsman/hugo-freelancer-theme/blob/master/exampleSite/data/projects/2014-07-13-project-1.yaml#L7) for the project examples. In the [modals.html](https://github.com/digitalcraftsman/hugo-freelancer-theme/blob/master/layouts/partials/modals.html#L29) partial file there is an anchor tag wrapped around the code, `<a href="#">{{ .category }}</a>` for that variable. I thought that this would act as a filter for different categories as seen in the [archetypes section ](https://gohugo.io/content/archetypes/) in the Hugo help docs, which is why I tried to create an archetype. Thanks again for your help, sorry if I confused you even more, it is not always easy to explain tech issues in a message.

**Comment by digitalcraftsman** [comment]
No problem. Now you've been more than exact.

You're right. There is no filter functionality at all. After revisiting this code I came to the conclusion that this is senseless. So, I've two options:
- either I remove them
- or I see this as a feature request and try to implement some sort of filter.

The question is, if this a common usecase? This same was originally intended as a small one-page theme for individuals. They've usually not a giant portfolio with a lot to filter. But I think this depends on your usecase. Let me know what you think.

**Comment by alanmcginnis** [comment]
I think you are right about the amount of content. I think filtering is not necessary but I wanted to give it a try if it was. I just removed the anchor tag and I am happy with the theme overall; just wanted to make sure I wasn't overlooking something. Thanks again for your quick replies and willingness to look into the issue!!

**Comment by digitalcraftsman** [comment]
I've removed the unused links inside the modals. See 1a26b522e0141e8f34767aacdcb2d6132a066ad8.
